### ISSUE TITLE
Plugin para WooCommerce

### ISSUE THREAD

**Issue by mariovalney** [Braspag/woocommerce#3]
Olá!

Há alguns anos criei um plugin para o WooCommerce se integrar com o Pagador.
Gostaria de saber se há interesse da Braspag em mantê-lo.

Atualmente ele está bem estável, mas seria interessante o apoio oficinal, principalmente para alterações futuras na API e criação de novas funcionalidades (além de poder usar o nome/marca da Braspag no começo do título). 

O plugin já está no repositório oficial e [aqui está o link](https://wordpress.org/plugins/woo-checkout-braspag) caso queiram dar uma olhada.

**Comment by devellop-labs** [comment]
O plugin oficial da Braspag é este módulo, qualquer sugestão de melhoria deve ser submetido neste repositório.

**Comment by mariovalney** [comment]
Entendo, mas esse plugin sequer está no repositório oficial ou segue os padrões de código do WordPress.
De qualquer forma, obrigado pelo feedback.
Abraços.
